[package]
name = "serial-monitor"
version = "0.0.5"
authors = ["Dave Hylands <dhylands@gmail.com>"]
license = "MIT"
keywords = ["serial", "communications", "terminal"]
categories = ["command-line-utilities"]
description = "Cross platform command line serial terminal program."
homepage = "https://github.com/dhylands/serial-monitor"
documentation = "https://github.com/dhylands/serial-monitor#serial-monitor"
repository = "https://github.com/dhylands/serial-monitor"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.18", features = ["event-stream"] }
futures = { version = "0.3" }
futures-timer = "3.0"
mio-serial = "3.3.1"
serialport = "3.3.0"
structopt = "0.3"
tokio = { version = "0.2.11", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tokio-serial = "4.3.3"
wildmatch = "1.0.9"
bytes = "0.5.4"
strum = { version = "0.19.5", features = ["derive"] }
